In [1]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

In [2]:
# File to Load
healthcare_csv = "../data/healthcare.csv"

#read csv
healthcare = pd.read_csv(healthcare_csv)

healthcare.head()

,state,hospital quality,preventable admissions,nursing home quality,medicare quality
0,Alabama,31,45,36,4
1,Alaska,36,4,1,1
2,Arizona,11,9,3,25
3,Arkansas,41,43,45,46
4,California,11,13,26,6

In [3]:
#Calculate Total Score 

healthcare['TotalScore'] = healthcare['hospital quality'] + healthcare['preventable admissions'] + healthcare['preventable admissions'] + healthcare['medicare quality']

#Average Rank Score
healthcare["healthcareRank"] = healthcare["TotalScore"].rank(method='min', ascending=True)

healthcare

,state,hospital quality,preventable admissions,nursing home quality,medicare quality,TotalScore,healthcareRank
0,Alabama,31,45,36,4,125,40.0
1,Alaska,36,4,1,1,45,4.0
2,Arizona,11,9,3,25,54,6.0
3,Arkansas,41,43,45,46,173,49.0
4,California,11,13,26,6,43,3.0
5,Colorado,24,5,11,12,46,5.0
6,Connecticut,9,21,16,35,86,14.0
7,Delaware,2,44,5,34,124,38.0
8,Florida,14,41,22,11,107,28.0
9,Georgia,25,40,47,33,138,42.0
10,Hawaii,15,1,2,8,25,1.0
11,Idaho,40,2,14,19,63,9.0
12,Illinois,21,37,38,15,110,31.0
13,Indiana,18,36,43,14,104,24.0
14,Iowa,48,14,31,39,115,34.0
15,Kansas,49,24,35,45,142,45.0
16,Kentucky,33,46,38,36,161,48.0
17,Louisiana,37,50,50,10,147,47.0
18,Maine,31,15,4,17,78,12.0
19,Maryland,1,19,17,21,60,7.0
20,Massachusetts,5,34,21,16,89,17.0
21,Michigan,17,30,23,50,127,41.0
22,Minnesota,41,49,7,2,141,44.0
23,Mississippi,43,48,42,37,176,50.0
24,Missouri,33,32,46,27,124,38.0
25,Montana,46,10,17,48,114,33.0
26,Nebraska,47,16,30,40,119,36.0
27,Nevada,37,20,25,28,105,25.0
28,New Hampshire,28,18,17,29,93,20.0
29,New Jersey,3,29,15,24,85,13.0
30,New Mexico,28,8,27,43,87,16.0
31,New York,5,23,34,38,89,17.0
32,North Carolina,11,33,38,18,95,21.0
33,North Dakota,50,25,17,3,103,23.0
34,Ohio,15,35,38,32,117,35.0
35,Oklahoma,37,38,48,26,139,43.0
36,Oregon,18,6,11,31,61,8.0
37,Pennsylvania,10,28,27,23,89,17.0
38,Rhode Island,8,22,8,49,101,22.0
39,South Carolina,5,31,31,42,109,29.0
40,South Dakota,45,27,23,7,106,26.0
41,Tennessee,22,42,37,5,111,32.0
42,Texas,25,39,48,20,123,37.0
43,Utah,27,3,6,9,42,2.0
44,Vermont,35,12,27,47,106,26.0
45,Virginia,4,26,31,30,86,14.0
46,Washington,18,7,13,41,73,11.0
47,West Virginia,28,47,43,22,144,46.0
48,Wisconsin,23,17,8,13,70,10.0
49,Wyoming,43,11,8,44,109,29.0

In [4]:
#export data
healthcare.to_csv("../output/healthcareRank.csv", index=False, header=True)